### ISSUE TITLE
Enhancement Requests 05-March-2020

### ISSUE THREAD

**Issue by wcharleswright** [kgellatl/COLDNet#1]
1. Replace node slider with option to save network as image
---Node slider is a great feature but unfortunately crashes the Shiny app when used to expand already large networks. (A given gene that returns a network of 100 genes will crash when the node slider is set to 2). Requesting that this feature be replaced in the same position by a 'download' button which allows user to save as SVG (or PNG of decent quality, better than that of right click > save image)

2. Requesting an option (as drop down menu) to load in multiple datasets. I will pre-compute several networks individually and same them all as RDS objects. I can load them all in within the first couple lines of code. The request is to have a dropdown at the top (ideally in line with the search box/Gene Matches box/node slider[save image] ) where a user can select Dataset1 or Dataset2 or Dataset3 etc, and have the corresponding test_net_1, test_net_2, or test_net_3 files load.

**Comment by kgellatl** [comment]
Hey Charlie I can get to these this weekend!
